# Site settings
title: Divyansh
email: divyansh.natani@gmail.com
baseurl: "/myWebsite"
url: ""
description: "
Hello, I am Divyansh Natani. Currently pursuing B.Tech from IIT Bombay. I belong to Jaipur aka Pink City, Rajasthan. A untrained pianoist, language learner, code lover, noob photographer and an explorer. Love exploring current-affairs and follow center-left ideology"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: MyWebsite

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url: https://www.facebook.com/divyansh.natani.142
  - title: instagram
    url: https://www.instagram.com/divyansh_natani/
  - title: linkedin
    url: https://www.linkedin.com/in/divyansh-natani-b59389193/
  - title: github
    url: https://github.com/DivyanshNatani

# Build settings
markdown: kramdown
permalink: pretty
