# Site settings
title: MyWebsite
email: nradhika106@gmail.com
baseurl: "/grayscale-theme"
url: ""
description: "
Currently pursuing B.Tech from IIT Bombay. I belong to Jaipur aka Pink City, Rajasthan. A untrained pianoist, language learner, code lover, noob photographer and an explorer. Love exploring current-affairs and follow center-left ideology"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/DivyanshNatani

# Build settings
markdown: kramdown
permalink: pretty
